import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@radix-ui/themes/styles.css';
import { Container, Theme } from '@radix-ui/themes';
import Navbar from './Navbar/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Theme accentColor='crimson' appearance='dark'>

          <Navbar />

          <Container px={{initial:"2", sm:"6",}}>
            {children}
          </Container>
          
          
        </Theme>
      </body>
    </html>
  )
}
